config/routes.rb
Mylinks::Application.routes.draw do
  
  controller :sessions do
    get  "/",  :action => :new,     :as => :login
    post "/",  :action => :create,  :as => false
    get  "/logout", :action => :destroy, :as => :logout
  end

  controller :dashboard do
    get "/my-links", :action => :index, :as => :dashboard
  end

  controller :link do
  	get "/new-link", :action => :new, :as => :links
  	post "/new-link", :action => :create
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :category, :link, :name, :user_id

  validates_presence_of :name, :category, :link, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :login, :name, :password

	def password=(password)
	  value = Digest::SHA1.hexdigest(password)
	  
	  write_attribute(:password, value)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private
  def logged_in?
  	current_user.present?
  end

  def current_user
  	@current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def require_logged_user
  	return if logged_in?
  	redirect_to login_path, :notice => "You must be logged in"
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :require_logged_user
	
	def index
		@facebook = Link.find_all_by_user_id_and_category(session[:user_id], 0).sort! { |a,b| b.id <=> a.id }
		@gag = Link.find_all_by_user_id_and_category(session[:user_id], 1).sort! { |a,b| b.id <=> a.id }
		@article = Link.find_all_by_user_id_and_category(session[:user_id], 2).sort! { |a,b| b.id <=> a.id }
		@technology = Link.find_all_by_user_id_and_category(session[:user_id], 3).sort! { |a,b| b.id <=> a.id }
		@other = Link.find_all_by_user_id_and_category(session[:user_id], 4).sort! { |a,b| b.id <=> a.id }
	end
end

app/controllers/link_controller.rb
class LinkController < ApplicationController
	before_filter :require_logged_user

	helper_method :category

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(params[:link])
		@link.user_id = session[:user_id]

		if @link.save
			redirect_to dashboard_path, notice: 'Link saved successfully'
		else
			render action: "new"
		end
	end

	private
	def category
		@category = [
			["Facebook", 0],
			["9GAG", 1],
			["Article", 2],
			["Technology", 3],
			["Other", 4]
		]
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false

  def new
  end

  def create
    reset_session

    user = User.find_by_login(params[:login])
    password_encripted = Digest::SHA1.hexdigest(params[:password])

    if user && user.password == password_encripted
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash.now[:notice] = "There was a mistake here. Please, try again"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.haml
#dashboard
	#linksBar
		= link_to image_tag("bt-new-link.png", :alt => "New link"), links_path

	#wrapperLinks
		- if @facebook.any?
			.categoryBar
				= image_tag "facebook-image.png", :alt => "Facebook"
				%span Facebook

			.contentLinks
				%ul
					- @facebook.each do |l|
						%li
							= link_to l.name, l.link, :target => "_blank"

		- if @gag.any?
			.categoryBar
				= image_tag "gag-image.png", :alt => "9GAG"
				%span 9GAG

			.contentLinks
				%ul
					- @gag.each do |l|
						%li
							= link_to l.name, l.link, :target => "_blank"

		- if @article.any?
			.categoryBar
				= image_tag "blog-image.png", :alt => "Article"
				%span Article

			.contentLinks
				%ul
					- @article.each do |l|
						%li
							= link_to l.name, l.link, :target => "_blank"

		- if @technology.any?
			.categoryBar
				= image_tag "technology-image.png", :alt => "Technology"
				%span Technology

			.contentLinks
				%ul
					- @technology.each do |l|
						%li
							= link_to l.name, l.link, :target => "_blank"

		- if @other.any?
			.categoryBar
				= image_tag "other-image.png", :alt => "Other"
				%span Other

			.contentLinks
				%ul
					- @other.each do |l|
						%li
							= link_to l.name, l.link, :target => "_blank"

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title MyLinks
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags

	%body
		#wrapper
			%header
				= link_to image_tag("mylinks-logo.png", :alt => "MyLinks"), dashboard_path, :id => "mylinksLogo"

				#rightHeader
					%span 
						welcome 
						%strong= current_user.name
					%span= link_to "logout [X]", logout_path

			%section
				= yield

app/views/link/new.html.haml
#linksBar

#wrapperForm
	= form_for @link do |f|
		- if @link.errors.any?
			#error_explanation
				%p#labelErrors Ops!
				%ul
					- @link.errors.full_messages.each do |msg|
						%li= msg

		%ul
			%li
				%label.text
					%span Name:
					= f.text_field :name

			%li
				%label
					%span Category:
					= f.select :category, category, { :prompt => "Choose one category" }

			%li
				%label.text
					%span Link:
					= f.text_field :link

			%li
				%span.submitButton
					= f.submit